CREATE TABLE categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL
);

CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(250) NOT NULL,
    name varchar(250) NOT NULL
);

CREATE TABLE events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2000),
    category_id INTEGER,
    confirmed_requests BIGINT NOT NULL,
    created_on timestamp,
    description varchar(7000),
    event_date timestamp,
    initiator_id BIGINT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER,
    published_on timestamp,
    request_moderation BOOLEAN NOT NULL,
    state varchar(200),
    title varchar(120),
    views BIGINT,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (initiator_id) REFERENCES users(id)
);

CREATE TABLE requests(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp,
    event_id BIGINT,
    requestor_id BIGINT,
    status varchar(20),
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (requestor_id) REFERENCES users (id),
    CONSTRAINT uq_request UNIQUE (event_id, requestor_id)
);


CREATE TABLE compilations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL UNIQUE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE compilation_events(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    FOREIGN KEY (event_id) REFERENCES events (id)
);

