CREATE TABLE endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    uri varchar(5000) NOT NULL,
    ip varchar(1000) NOT NULL,
    time_hit timestamp NOT NULL
);
